# Generated by Django 4.2.3 on 2023-07-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_tg_id', models.IntegerField(verbose_name='ID пользователя')),
                ('client_tg_username', models.CharField(max_length=200, verbose_name='Имя пользователя')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
