# Generated by Django 4.2.3 on 2023-07-20 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_tg_id', models.IntegerField(verbose_name='ID пользователя')),
                ('client_tg_username', models.CharField(max_length=200, verbose_name='Имя пользователя')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='CustomizedCake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levels', models.IntegerField(verbose_name='Количество уровней торта')),
                ('shape', models.CharField(max_length=20, verbose_name='Форма торта')),
                ('toping', models.CharField(max_length=30, verbose_name='Топпинг')),
                ('berries', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ягоды')),
                ('decore', models.CharField(blank=True, max_length=30, null=True, verbose_name='Декор')),
            ],
            options={
                'verbose_name': 'Кастомизированный торт',
                'verbose_name_plural': 'Кастомизированные торты',
            },
        ),
        migrations.CreateModel(
            name='ReadyCake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cake_name', models.CharField(max_length=200, verbose_name='Название торта')),
                ('cake_price', models.IntegerField(verbose_name='Цена торта')),
                ('cake_image', models.ImageField(upload_to='cake_image', verbose_name='Изображение торта')),
            ],
            options={
                'verbose_name': 'Готовый торт',
                'verbose_name_plural': 'Готовые торты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Адресс заказа')),
                ('delivery_date', models.DateField(verbose_name='Дата доставки')),
                ('delivery_time', models.TimeField(verbose_name='Время доставки')),
                ('promocode', models.CharField(blank=True, max_length=50, null=True, verbose_name='Промокод')),
                ('is_active', models.BooleanField(blank=True, null=True, verbose_name='Готов ли заказ')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу')),
                ('inscription', models.TextField(blank=True, help_text='Мы можем разместить на торте любую надпись, например: «С днем рождения!»', max_length=15, null=True, verbose_name='Надпись на торте')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cake_app.client', verbose_name='Клиент')),
                ('customizedcake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cake_app.customizedcake')),
                ('readycake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cake_app.readycake')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
