# Generated by Django 4.2.3 on 2023-07-20 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cake_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customizedcake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cake_app.customizedcake', verbose_name='Торт, собранный самостоятельно'),
        ),
        migrations.AlterField(
            model_name='order',
            name='readycake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cake_app.readycake', verbose_name='Готовый торт'),
        ),
    ]
