# Generated by Django 4.2.3 on 2023-07-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake_app', '0002_alter_order_customizedcake_alter_order_readycake'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizedcake',
            name='filling',
            field=models.CharField(default='Всбитые сливки', max_length=20, verbose_name='Начинка'),
        ),
    ]
