# Generated by Django 4.2.3 on 2023-07-19 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cake_app', '0003_alter_order_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadyCake',
            fields=[
                ('cake_name', models.CharField(max_length=200, verbose_name='Название торта')),
                ('cake_price', models.IntegerField(verbose_name='Цена торта')),
                ('inscription', models.TextField(blank=True, help_text='Мы можем разместить на торте любую надпись, например: «С днем рождения!»', null=True, verbose_name='Надпись на торте')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cake_app.order')),
            ],
            options={
                'verbose_name': 'Готовый торт',
                'verbose_name_plural': 'Готовые торты',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(blank=True, null=True, verbose_name='Готов ли заказ'),
        ),
    ]
