# Generated by Django 4.2.3 on 2023-07-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake_app', '0003_customizedcake_filling'),
    ]

    operations = [
        migrations.AddField(
            model_name='readycake',
            name='topping',
            field=models.CharField(blank=True, choices=[('Без топпинга', 'Без топпинга'), ('Белый соус', 'Белый соус'), ('Карамельный сироп', 'Карамельный сироп'), ('Кленовый сироп', 'Кленовый сироп'), ('Клубничный сироп', 'Клубничный сироп'), ('Черничный сироп', 'Черничный сироп'), ('Молочный шоколад', 'Молочный шоколад')], default='Без топпинга', max_length=50, verbose_name='Топпинг'),
        ),
        migrations.AlterField(
            model_name='customizedcake',
            name='berries',
            field=models.CharField(blank=True, choices=[('Без ягод', 'Без ягод'), ('Ежевика', 'Ежевика'), ('Малина', 'Малина'), ('Голубика', 'Голубика'), ('Клубника', 'Клубника')], default='Без ягод', max_length=50, null=True, verbose_name='Ягоды'),
        ),
        migrations.AlterField(
            model_name='customizedcake',
            name='decore',
            field=models.CharField(blank=True, choices=[('Без декора', 'Без декора'), ('Фисташки', 'Фисташки'), ('Безе', 'Безе'), ('Фундук', 'Фундук'), ('Пекан', 'Пекан'), ('Маршмеллоу', 'Маршмеллоу'), ('Марципан', 'Марципан')], default='Без декора', max_length=50, null=True, verbose_name='Декор'),
        ),
        migrations.AlterField(
            model_name='customizedcake',
            name='filling',
            field=models.CharField(choices=[('Манго-малина', 'Манго-малина'), ('Йогуртовый с вишней', 'Йогуртовый с вишней'), ('КарамельШоколад', 'КарамельШоколад'), ('Рафаэло', 'Рафаэло'), ('Сливочно-фруктовая', 'Сливочно-фруктовая'), ('Диетическая с клубникой', 'Диетическая с клубникой')], default='Сливочно-фруктовая', max_length=50, verbose_name='Начинка'),
        ),
        migrations.AlterField(
            model_name='customizedcake',
            name='levels',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1, verbose_name='Количество уровней торта'),
        ),
        migrations.AlterField(
            model_name='customizedcake',
            name='shape',
            field=models.CharField(choices=[('Квадрат', 'Квадрат'), ('Круг', 'Круг'), ('Прямоугольник', 'Прямоугольник')], default='Круг', max_length=50, verbose_name='Форма торта'),
        ),
        migrations.AlterField(
            model_name='customizedcake',
            name='toping',
            field=models.CharField(choices=[('Без топпинга', 'Без топпинга'), ('Белый соус', 'Белый соус'), ('Карамельный сироп', 'Карамельный сироп'), ('Кленовый сироп', 'Кленовый сироп'), ('Клубничный сироп', 'Клубничный сироп'), ('Черничный сироп', 'Черничный сироп'), ('Молочный шоколад', 'Молочный шоколад')], default='Без топпинга', max_length=50, verbose_name='Топпинг'),
        ),
    ]
