# Generated by Django 2.2.24 on 2023-07-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake_app', '0003_customizedcake_filling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customizedcake',
            name='filling',
            field=models.CharField(default='Взбитые сливки', max_length=20, verbose_name='Начинка'),
        ),
        migrations.AlterField(
            model_name='customizedcake',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='readycake',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
