# Generated by Django 4.2.3 on 2023-07-19 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cake_app', '0004_readycake_alter_order_comment_alter_order_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizedCake',
            fields=[
                ('levels', models.IntegerField(verbose_name='Количество уровней торта')),
                ('shape', models.CharField(max_length=20, verbose_name='Форма торта')),
                ('toping', models.TextField(verbose_name='Топпинг')),
                ('berries', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ягоды')),
                ('decore', models.CharField(blank=True, max_length=100, null=True, verbose_name='Декор')),
                ('inscription', models.TextField(blank=True, help_text='Мы можем разместить на торте любую надпись, например: «С днем рождения!»', null=True, verbose_name='Надпись на торте')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cake_app.order')),
            ],
            options={
                'verbose_name': 'Кастомизированный торт',
                'verbose_name_plural': 'Кастомизированные торты',
            },
        ),
    ]
