# Generated by Django 4.2.3 on 2023-07-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake_app', '0005_readycake_topping_alter_client_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.IntegerField(verbose_name='ID пользователя')),
                ('tg_username', models.CharField(max_length=200, verbose_name='Имя пользователя')),
            ],
            options={
                'verbose_name': 'Кондитер',
                'verbose_name_plural': 'Кондитеры',
            },
        ),
    ]
