# Generated by Django 4.2.3 on 2023-07-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake_app', '0005_customizedcake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizedcake',
            name='decore',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Декор'),
        ),
        migrations.AlterField(
            model_name='customizedcake',
            name='toping',
            field=models.CharField(max_length=30, verbose_name='Топпинг'),
        ),
    ]
